name: Deploy Next.js to Kubernetes

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nextjs-portfolio

    steps:

      # --------------------------------------------------
      # 1. Checkout Source
      # --------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2. Generate Short Commit SHA
      # Example: a1b2c3d
      # --------------------------------------------------
      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # --------------------------------------------------
      # 3. Login Docker Hub
      # --------------------------------------------------
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
          | docker login \
              -u "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin

      # --------------------------------------------------
      # 4. Build Docker Image
      # --------------------------------------------------
      - name: Build Docker Image
        run: |
          docker build \
            -t $IMAGE_NAME:$IMAGE_TAG \
            .

      # --------------------------------------------------
      # 5. Push Docker Image
      # --------------------------------------------------
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      # --------------------------------------------------
      # 6. Deploy to Kubernetes
      # --------------------------------------------------
      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            set -e

            IMAGE=${{ secrets.DOCKER_USERNAME }}/nextjs-portfolio:${{ env.IMAGE_TAG }}

            echo "================================="
            echo "Deploying Image:"
            echo "$IMAGE"
            echo "================================="

            kubectl set image deployment/portfolio \
              portfolio=$IMAGE \
              -n portfolio

            kubectl rollout status deployment/portfolio \
              -n portfolio

            echo ""
            echo "Deployment Successful!"